// cards.js

// A base de dados agora está organizada por montadora para facilitar a manutenção.
const manufacturers = {
    "McLaren": {
        P1: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=McLaren+P1',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=McLaren',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'McLaren P1',
            montadora: 'McLaren', // Adicionado para referência interna
            classe: "S",
            ano: 2013,
            pais: 'Reino Unido',
            velocidade: 350,
            aceleracao: 2.8,
            direcao: 95,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        }
    },
    "Lamborghini": {
        Aventador: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=Aventador',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Lambo',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=IT',
            nome: 'Lamborghini Aventador',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2011,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.9,
            direcao: 92,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        }
    },
    "Bugatti": {
        Chiron: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=Chiron',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Bugatti',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=FR',
            nome: 'Bugatti Chiron',
            montadora: 'Bugatti',
            classe: "S+",
            ano: 2016,
            pais: 'França',
            velocidade: 420,
            aceleracao: 2.5,
            direcao: 88,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        }
    },
    "Toyota": {
       Supra_MK5: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK5.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK5 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 2022,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.5,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Supra_MK4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK4 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 1995,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.6,
            direcao: 77,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Corolla_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAGRCorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR 1.6',
            montadora: 'Toyota',
            classe: "B",
            ano: 2024,
            pais: 'Japão',
            velocidade: 230,
            aceleracao: 5.5,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Corolla: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Altis 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_GR_Sport: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        Camry: {
            imagem: './Imgs_Carros/Toyota/TOYOTACamry.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Camry XLE 3.5 V6',
            montadora: 'Toyota',
            classe: "C",
            ano: 2020,
            pais: 'Japão',
            velocidade: 225,
            aceleracao: 7,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCross.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross XRX 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCrossGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        RAV4: {
            imagem: './Imgs_Carros/Toyota/TOYOTARAV4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'RAV4 2.5 PHEV',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 6,
            direcao: 75,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        AE86: {
            imagem: './Imgs_Carros/Toyota/TOYOTAAE86.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Toyota AE86 BEV',
            montadora: 'Toyota',
            classe: "D",
            ano: 1986,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 8.9,
            direcao: 57,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        SW4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 SRX Platinum 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        SW4_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4GR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 GR Sport 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Hilux: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHilux.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 12,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Hilux_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHiluxGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 10.7,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Yaris_Sedan: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisSedan.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Sedan XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 182,
            aceleracao: 11.8,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yaris_Hatch: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisHatch.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Hatch XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "Nissan": {
        Skyline_r34: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=Skyline+R34',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Nissan',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=JP',
            nome: 'Nissan Skyline GT-R R34',
            montadora: 'Nissan',
            classe: "A",
            ano: 1999,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.9,
            direcao: 88,
            altura: 'Baixo',
            pneus: 'Esportivo',
            tracao: '4x4'
        }
    },
    "Mazda": {
        Rx7: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=RX-7+FD',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Mazda',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=JP',
            nome: 'Mazda RX-7 FD',
            montadora: 'Mazda',
            classe: "A",
            ano: 1992,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 5.3,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Esportivo',
            tracao: 'Traseira'
        }
    },
    "Byd": {
        Han_Ev: {
            imagem: './Imgs_Carros/Byd/BYDHanEv.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Han Ev',
            montadora: 'Byd',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 186,
            aceleracao: 3.9,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Tan_EV: {
            imagem: './Imgs_Carros/Byd/BYDTanEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tan EV',
            montadora: 'Byd',
            classe: "B",
            ano: 2023,
            pais: 'China',
            velocidade: 186,
            aceleracao: 4.6,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Song_Plus: {
            imagem: './Imgs_Carros/Byd/BYDSongPlus.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Song Plus DM-i 1.5',
            montadora: 'Byd',
            classe: "C",
            ano: 2024,
            pais: 'China',
            velocidade: 170,
            aceleracao: 8.5,
            direcao: 79,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yuan_Plus_EV: {
            imagem: './Imgs_Carros/Byd/BYDYuanPlusEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Yuan Plus EV',
            montadora: 'Byd',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 7.3,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin: {
            imagem: './Imgs_Carros/Byd/BYDDolphin.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Diamond',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 10.9,
            direcao: 65,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin_Mini: {
            imagem: './Imgs_Carros/Byd/BYDDolphinMini.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Mini EV',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 130,
            aceleracao: 14.9,
            direcao: 63,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "GWM": {
        Haval_H6_GT: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6GT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 GT 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.8,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Haval_H6: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 Premium 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.9,
            direcao: 76,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Ora_GT: {
            imagem: './Imgs_Carros/GWM/GWMOraGT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Ora 03 GT',
            montadora: 'GWM',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 8.2,
            direcao: 70,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        }
    },
    "Ford": {
        Mustang_GT500: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=GT500',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Ford',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Ford Mustang Shelby GT500',
            montadora: 'Ford',
            classe: "A",
            ano: 2020,
            pais: 'EUA',
            velocidade: 290,
            aceleracao: 3.5,
            direcao: 82,
            altura: 'Médio',
            pneus: 'Rua',
            tracao: 'Traseira'
        }
    },
    "Chevrolet": {
        Camaro_ZL1: {
            imagem: 'https://placehold.co/600x400/111827/ffffff?text=Camaro+ZL1',
            logo: 'https://placehold.co/100x40/ffffff/000000?text=Chevrolet',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevrolet Camaro ZL1',
            montadora: 'Chevrolet',
            classe: "A",
            ano: 2017,
            pais: 'EUA',
            velocidade: 318,
            aceleracao: 3.5,
            direcao: 84,
            altura: 'Médio',
            pneus: 'Rua',
            tracao: 'Traseira'
        },
        CorvetteZ062015: {
            imagem: './Imgs_Carros/Chevrolet/CorvetteZ062015.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2015,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 3,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        }
    }
};

// **A MÁGICA ACONTECE AQUI**
// Nós criamos um objeto 'cards' plano a partir da estrutura de montadoras.
// Isso garante que o resto do seu aplicativo continue funcionando sem precisar de nenhuma alteração.
const allCards = {};
for (const manufacturer in manufacturers) {
    Object.assign(allCards, manufacturers[manufacturer]);
}

// Exportamos o objeto plano para manter a compatibilidade.
export const cards = allCards;
