// cards.js

// A base de dados agora está organizada por montadora para facilitar a manutenção.
const manufacturers = {
    "Toyota": {
        Supra_MK5: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK5.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK5 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 2022,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.5,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Supra_MK4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK4 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 1995,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.6,
            direcao: 77,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Corolla_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAGRCorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR 1.6',
            montadora: 'Toyota',
            classe: "B",
            ano: 2024,
            pais: 'Japão',
            velocidade: 230,
            aceleracao: 5.5,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Corolla: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Altis 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_GR_Sport: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        Camry: {
            imagem: './Imgs_Carros/Toyota/TOYOTACamry.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Camry XLE 3.5 V6',
            montadora: 'Toyota',
            classe: "C",
            ano: 2020,
            pais: 'Japão',
            velocidade: 225,
            aceleracao: 7,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCross.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross XRX 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCrossGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        RAV4: {
            imagem: './Imgs_Carros/Toyota/TOYOTARAV4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'RAV4 2.5 PHEV',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 6,
            direcao: 75,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        AE86: {
            imagem: './Imgs_Carros/Toyota/TOYOTAAE86.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Toyota AE86 BEV',
            montadora: 'Toyota',
            classe: "D",
            ano: 1986,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 8.9,
            direcao: 57,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        SW4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 SRX Platinum 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        SW4_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4GR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 GR Sport 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Hilux: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHilux.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 12,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Hilux_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHiluxGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 10.7,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Yaris_Sedan: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisSedan.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Sedan XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 182,
            aceleracao: 11.8,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yaris_Hatch: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisHatch.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Hatch XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "Byd": {
        Yangwang_U9: {
            imagem: './Imgs_Carros/Byd/BYDYangwang_U9.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Yangwang U9',
            montadora: 'Byd',
            classe: "R",
            ano: 2024,
            pais: 'China',
            velocidade: 472,
            aceleracao: 2.3,
            direcao: 93,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Han_Ev: {
            imagem: './Imgs_Carros/Byd/BYDHanEv.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Han Ev',
            montadora: 'Byd',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 186,
            aceleracao: 3.9,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Tan_EV: {
            imagem: './Imgs_Carros/Byd/BYDTanEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tan EV',
            montadora: 'Byd',
            classe: "B",
            ano: 2023,
            pais: 'China',
            velocidade: 186,
            aceleracao: 4.6,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Seal: {
            imagem: './Imgs_Carros/Byd/BYDSeal.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Seal',
            montadora: 'Byd',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 3.8,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Shark: {
            imagem: './Imgs_Carros/Byd/BYDShark.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Shark',
            montadora: 'Byd',
            classe: "B",
            ano: 2025,
            pais: 'China',
            velocidade: 160,
            aceleracao: 5.7,
            direcao: 80,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Song_Plus: {
            imagem: './Imgs_Carros/Byd/BYDSongPlus.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Song Plus DM-i 1.5',
            montadora: 'Byd',
            classe: "C",
            ano: 2024,
            pais: 'China',
            velocidade: 170,
            aceleracao: 8.5,
            direcao: 79,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Song_Plus2026: {
            imagem: './Imgs_Carros/Byd/BYDSongPlus2026.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Song Plus DM-i 1.5',
            montadora: 'Byd',
            classe: "C",
            ano: 2026,
            pais: 'China',
            velocidade: 170,
            aceleracao: 7.9,
            direcao: 81,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yuan_Plus_EV: {
            imagem: './Imgs_Carros/Byd/BYDYuanPlusEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Yuan Plus EV',
            montadora: 'Byd',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 7.3,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin: {
            imagem: './Imgs_Carros/Byd/BYDDolphin.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Diamond',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 10.9,
            direcao: 65,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin_Mini: {
            imagem: './Imgs_Carros/Byd/BYDDolphinMini.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Mini EV',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 130,
            aceleracao: 14.9,
            direcao: 63,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "GWM": {
        Haval_H6_GT: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6GT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 GT 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.8,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Haval_H6: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 Premium 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.9,
            direcao: 76,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Ora_GT: {
            imagem: './Imgs_Carros/GWM/GWMOraGT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Ora 03 GT',
            montadora: 'GWM',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 8.2,
            direcao: 70,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        }
    },
    "Bugatti": {
        EB_110: {
            imagem: './Imgs_Carros/Bugatti/BugattiEB110.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'EB 110',
            montadora: 'Bugatti',
            classe: "S",
            ano: 1992,
            pais: 'França',
            velocidade: 341,
            aceleracao: 4.5,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Veyron: {
            imagem: './Imgs_Carros/Bugatti/BugattiVeyron.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Veyron',
            montadora: 'Bugatti',
            classe: "S",
            ano: 2006,
            pais: 'França',
            velocidade: 407,
            aceleracao: 2.5,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Chiron: {
            imagem: './Imgs_Carros/Bugatti/BugattiChiron.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Chiron',
            montadora: 'Bugatti',
            classe: "S",
            ano: 2017,
            pais: 'França',
            velocidade: 420,
            aceleracao: 2.4,
            direcao: 89,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Divo: {
            imagem: './Imgs_Carros/Bugatti/BugattiDivo.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Divo',
            montadora: 'Bugatti',
            classe: "S",
            ano: 2019,
            pais: 'França',
            velocidade: 380,
            aceleracao: 2.4,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Centodieci: {
            imagem: './Imgs_Carros/Bugatti/BugattiCentodieci.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Centodieci',
            montadora: 'Bugatti',
            classe: "S",
            ano: 2022,
            pais: 'França',
            velocidade: 380,
            aceleracao: 2.4,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Bolide: {
            imagem: './Imgs_Carros/Bugatti/BugattiBolide.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Bolide',
            montadora: 'Bugatti',
            classe: "X",
            ano: 2024,
            pais: 'França',
            velocidade: 500,
            aceleracao: 2.1,
            direcao: 105,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Mistral: {
            imagem: './Imgs_Carros/Bugatti/BugattiMistral.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Mistral',
            montadora: 'Bugatti',
            classe: "R",
            ano: 2024,
            pais: 'França',
            velocidade: 450,
            aceleracao: 2.4,
            direcao: 99,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Vision_GT: {
            imagem: './Imgs_Carros/Bugatti/BugattiVisionGT.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Vision GT',
            montadora: 'Bugatti',
            classe: "R",
            ano: 2015,
            pais: 'França',
            velocidade: 448,
            aceleracao: 2.5,
            direcao: 103,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        La_Voiture_Noire: {
            imagem: './Imgs_Carros/Bugatti/BugattiLaVoitureNoire.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'La Voiture Noire',
            montadora: 'Bugatti',
            classe: "R",
            ano: 2019,
            pais: 'França',
            velocidade: 420,
            aceleracao: 2.4,
            direcao: 88,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Tourbillon: {
            imagem: './Imgs_Carros/Bugatti/BugattiTourbillon.png',
            logo: './assets/Bugatti-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=França',
            nome: 'Tourbillon',
            montadora: 'Bugatti',
            classe: "R",
            ano: 2026,
            pais: 'França',
            velocidade: 445,
            aceleracao: 2.0,
            direcao: 95,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        }
    },
    "Chery": {
        Tiggo_8_Pro: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo8Pro.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 8 Pro Hybrid 1.5',
            montadora: 'Chery',
            classe: "C",
            ano: 2025,
            pais: 'China',
            velocidade: 180,
            aceleracao: 7,
            direcao: 72,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Tiggo_7_Sport: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo7Sport.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 7 Sport 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 180,
            aceleracao: 10.3,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Tiggo_5x_Sport: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo5xSport.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 5x Sport 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 193,
            aceleracao: 10.7,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Arrizo_5: {
            imagem: './Imgs_Carros/Chery/CHERYArrizo5.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Arrizo 5 RXS 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2021,
            pais: 'China',
            velocidade: 190,
            aceleracao: 9.9,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Arrizo_6_Pro: {
            imagem: './Imgs_Carros/Chery/CHERYArrizo6Pro.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Arrizo 6 Pro Hybrid 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 190,
            aceleracao: 9,
            direcao: 71,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        QQ: {
            imagem: './Imgs_Carros/Chery/CHERYQQ.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'QQ Look 1.0',
            montadora: 'Chery',
            classe: "E",
            ano: 2020,
            pais: 'China',
            velocidade: 165,
            aceleracao: 14,
            direcao: 59,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        iCar: {
            imagem: './Imgs_Carros/Chery/CHERYiCar.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'iCar EQ1 Tech',
            montadora: 'Chery',
            classe: "E",
            ano: 2021,
            pais: 'China',
            velocidade: 120,
            aceleracao: 12.9,
            direcao: 60,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
    },
    "LandRover": {
        Range_Rover_Sport: {
            imagem: './Imgs_Carros/LandRover/LANDROVERRangeRoverSport.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Range Rover Sport Dynamic',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 234,
            aceleracao: 5.9,
            direcao: 74,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Discovery: {
            imagem: './Imgs_Carros/LandRover/LANDROVERDiscovery.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Discovery R-Dynamic 3.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "C",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 209,
            aceleracao: 6.8,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Evoque: {
            imagem: './Imgs_Carros/LandRover/LANDROVEREvoque.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Evoque HSE Dynamic 2.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "C",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 230,
            aceleracao: 7.5,
            direcao: 73,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Range_Rover: {
            imagem: './Imgs_Carros/LandRover/LANDROVERRangeRover.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Range Rover Vogue SE 5.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2015,
            pais: 'Reino Unido',
            velocidade: 250,
            aceleracao: 5.5,
            direcao: 71,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Velar: {
            imagem: './Imgs_Carros/LandRover/LANDROVERVelar.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Velar R-Dynamic HSE 2.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 209,
            aceleracao: 5.4,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Defender: {
            imagem: './Imgs_Carros/LandRover/LANDROVERDefender.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Defender 130 X 3.00',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "D",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 191,
            aceleracao: 7.5,
            direcao: 72,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Freelander: {
            imagem: './Imgs_Carros/LandRover/LANDROVERFreelander.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Freelander HSE 2.2',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "D",
            ano: 2015,
            pais: 'Reino Unido',
            velocidade: 190,
            aceleracao: 9.5,
            direcao: 66,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        }
    },
    "Chevrolet": {
        CorvetteZ062015: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062015.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2015,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 3,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        CorvetteZ062023: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062023.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 5.5 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2023,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 2.8,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Corvette_Stingray: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteStingray.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Stingray 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2020,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 3,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        CorvetteZ062006: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062006.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 7.0 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2006,
            pais: 'EUA',
            velocidade: 305,
            aceleracao: 5.1,
            direcao: 73,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Camaro_Collection: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroCollection.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro Collection 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2024,
            pais: 'EUA',
            velocidade: 290,
            aceleracao: 4.2,
            direcao: 84,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Camaro_SS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroSS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro SS 6.2 V8',
            montadora: 'Chevrolet',
            classe: "A",
            ano: 2012,
            pais: 'EUA',
            velocidade: 250,
            aceleracao: 4.8,
            direcao: 81,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Camaro_Conversível_SS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroConversívelSS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro Conversível SS 6.2',
            montadora: 'Chevrolet',
            classe: "A",
            ano: 2019,
            pais: 'EUA',
            velocidade: 250,
            aceleracao: 4.2,
            direcao: 83,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Silverado: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETSilverado.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Silverado High Country 5.3',
            montadora: 'Chevrolet',
            classe: "C",
            ano: 2024,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 7.4,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Cruze_Hatch_RS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCruzeHatch.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Cruze Hatch RS 1.4 Turbo',
            montadora: 'Chevrolet',
            classe: "C",
            ano: 2024,
            pais: 'EUA',
            velocidade: 214,
            aceleracao: 9,
            direcao: 73,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        S10_2025: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETS102025.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'S10 High Country 2.8',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 9.4,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Trail_Blazer: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETTrailBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'TrailBlazer Premier 2.8',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2024,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 10.3,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Equinox: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETEquinox.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Equinox Premier 1.5',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2024,
            pais: 'EUA',
            velocidade: 196,
            aceleracao: 9.2,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Onix_Sedan: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOnixSedan.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Onix Sedan Premier 1.0',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 187,
            aceleracao: 10.4,
            direcao: 69,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Onix_RS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOnixRS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Onix RS 1.0 Turbo',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 187,
            aceleracao: 10.1,
            direcao: 71,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        Bolt: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETBolt.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Bolt Premier',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2022,
            pais: 'EUA',
            velocidade: 146,
            aceleracao: 7.3,
            direcao: 67,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Celta: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCelta.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Celta LT 1.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2015,
            pais: 'EUA',
            velocidade: 161,
            aceleracao: 13.4,
            direcao: 56,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Agile: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETAgile.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Agile Effect 1.4',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2014,
            pais: 'EUA',
            velocidade: 177,
            aceleracao: 10.9,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Astra: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETAstra.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Astra Advantage 2.0 8V',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2011,
            pais: 'EUA',
            velocidade: 200,
            aceleracao: 9.8,
            direcao: 64,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Blazer_2011: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Blazer Advantage 2.4',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2011,
            pais: 'EUA',
            velocidade: 150,
            aceleracao: 11.9,
            direcao: 60,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Grand_Blazer: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETGrandBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Grand Blazer 4.2',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2000,
            pais: 'EUA',
            velocidade: 150,
            aceleracao: 18,
            direcao: 56,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Monza: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETMonza.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Monza GLS 2.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1996,
            pais: 'EUA',
            velocidade: 172,
            aceleracao: 11.7,
            direcao: 67,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Chevy_500: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevy500.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevy 500 DL 1.6',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1995,
            pais: 'EUA',
            velocidade: 140,
            aceleracao: 18.5,
            direcao: 50,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Chevette_Junior: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevetteJunior.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevette Junior 1.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1993,
            pais: 'EUA',
            velocidade: 131,
            aceleracao: 21.6,
            direcao: 60,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Opala: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOpala.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Opala SL 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 169,
            aceleracao: 12,
            direcao: 65,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Caravan_Comodoro: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCaravanComodoro.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Caravan Comodoro 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 168,
            aceleracao: 12.1,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Caravan_Diplomata: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCaravanDiplomata.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Caravan Diplomata 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 168,
            aceleracao: 12.1,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Chevette_1990: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevette1990.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevette SL 1.6',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1990,
            pais: 'EUA',
            velocidade: 151,
            aceleracao: 14.1,
            direcao: 57,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
    },
    "Lamborghini": {
        GT_350: {
            imagem: './Imgs_Carros/Lamborghini/Lambo350GT.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '350 GT',
            montadora: 'Lamborghini',
            classe: "B",
            ano: 1965,
            pais: 'Itália',
            velocidade: 240,
            aceleracao: 6.8,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Athon: {
            imagem: './Imgs_Carros/Lamborghini/LamboAthon.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Athon',
            montadora: 'Lamborghini',
            classe: "B",
            ano: 1980,
            pais: 'Itália',
            velocidade: 260,
            aceleracao: 5.8,
            direcao: 55,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Aventador_LP_700_4: {
            imagem: './Imgs_Carros/Lamborghini/LamboAventadorLP7004.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Aventador LP 700-4',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2016,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.9,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Aventador_SVJ: {
            imagem: './Imgs_Carros/Lamborghini/LamboAventadorSVJ.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Aventador SVJ',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2022,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.8,
            direcao: 89,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Cala: {
            imagem: './Imgs_Carros/Lamborghini/LamboCala.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Calà',
            montadora: 'Lamborghini',
            classe: "A",
            ano: 1995,
            pais: 'Itália',
            velocidade: 291,
            aceleracao: 4.9,
            direcao: 70,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Countach: {
            imagem: './Imgs_Carros/Lamborghini/LamboCountach.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Countach',
            montadora: 'Lamborghini',
            classe: "A",
            ano: 1989,
            pais: 'Itália',
            velocidade: 295,
            aceleracao: 5.0,
            direcao: 68,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Diablo: {
            imagem: './Imgs_Carros/Lamborghini/LamboDiablo.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Diablo',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 1996,
            pais: 'Itália',
            velocidade: 325,
            aceleracao: 4.1,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Espada_Series_III: {
            imagem: './Imgs_Carros/Lamborghini/LamboEspadaSeriesIII.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Espada Series III',
            montadora: 'Lamborghini',
            classe: "B",
            ano: 1978,
            pais: 'Itália',
            velocidade: 250,
            aceleracao: 6.1,
            direcao: 66,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Estoque: {
            imagem: './Imgs_Carros/Lamborghini/LamboEstoque.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Estoque',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2008,
            pais: 'Itália',
            velocidade: 322,
            aceleracao: 3.0,
            direcao: 73,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Gallardo: {
            imagem: './Imgs_Carros/Lamborghini/LamboGallardo.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Gallardo',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2005,
            pais: 'Itália',
            velocidade: 309,
            aceleracao: 4.2,
            direcao: 79,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Gallardo_LP_560: {
            imagem: './Imgs_Carros/Lamborghini/LamboGallardoLP560.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Gallardo LP 560',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2013,
            pais: 'Itália',
            velocidade: 325,
            aceleracao: 3.7,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Huracan: {
            imagem: './Imgs_Carros/Lamborghini/LamboHuracan.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Huracán',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2022,
            pais: 'Itália',
            velocidade: 325,
            aceleracao: 3.2,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Huracan_STO: {
            imagem: './Imgs_Carros/Lamborghini/LamboHuracanSTO.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Huracán STO',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2022,
            pais: 'Itália',
            velocidade: 311,
            aceleracao: 3.0,
            direcao: 84,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Murcielago_LP640: {
            imagem: './Imgs_Carros/Lamborghini/LamboMurcielagoLP640.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Murciélago LP640',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2009,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 3.4,
            direcao: 81,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Sian_FKP_37: {
            imagem: './Imgs_Carros/Lamborghini/LamboSianFKP37.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Sián FKP 37',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2020,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.8,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        LM002: {
            imagem: './Imgs_Carros/Lamborghini/LamboLM002.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'LM002',
            montadora: 'Lamborghini',
            classe: "C",
            ano: 1990,
            pais: 'Itália',
            velocidade: 201,
            aceleracao: 8.5,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Miura: {
            imagem: './Imgs_Carros/Lamborghini/LamboMiura.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Miura',
            montadora: 'Lamborghini',
            classe: "A",
            ano: 1968,
            pais: 'Itália',
            velocidade: 282,
            aceleracao: 4.6,
            direcao: 65,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Reventon: {
            imagem: './Imgs_Carros/Lamborghini/LamboReventon.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Reventón',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2008,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 3.4,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Sesto_Elemento: {
            imagem: './Imgs_Carros/Lamborghini/LamboSestoElemento.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Sesto Elemento',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2010,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.5,
            direcao: 95,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Urus: {
            imagem: './Imgs_Carros/Lamborghini/LamboUrus.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Urus',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2022,
            pais: 'Itália',
            velocidade: 305,
            aceleracao: 3.6,
            direcao: 79,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Veneno: {
            imagem: './Imgs_Carros/Lamborghini/LamboVeneno.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Veneno',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2013,
            pais: 'Itália',
            velocidade: 355,
            aceleracao: 2.8,
            direcao: 88,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Countach_LPI800_4: {
            imagem: './Imgs_Carros/Lamborghini/LamboCountachLPI8004.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Countach LPI800-4',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2022,
            pais: 'Itália',
            velocidade: 355,
            aceleracao: 2.8,
            direcao: 83,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Centenario: {
            imagem: './Imgs_Carros/Lamborghini/LamboCentenario.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Centenário',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2016,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.8,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        SC18_Alston: {
            imagem: './Imgs_Carros/Lamborghini/LamboSC18Alston.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'SC18 Alston',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2018,
            pais: 'Itália',
            velocidade: 354,
            aceleracao: 2.7,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Essenza_SCV12: {
            imagem: './Imgs_Carros/Lamborghini/LamboEssenzaSCV12.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Essenza SCV12',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2020,
            pais: 'Itália',
            velocidade: 345,
            aceleracao: 2.5,
            direcao: 98,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Invencible: {
            imagem: './Imgs_Carros/Lamborghini/LamboInvencible.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Invencible',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2023,
            pais: 'Itália',
            velocidade: 335,
            aceleracao: 2.8,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Temerario: {
            imagem: './Imgs_Carros/Lamborghini/LamboTemerario.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Temerario',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 343,
            aceleracao: 2.7,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Revuelto: {
            imagem: './Imgs_Carros/Lamborghini/LamboRevuelto.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Revuelto',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.5,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Fenomeno: {
            imagem: './Imgs_Carros/Lamborghini/LamboFenomeno.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Fenomeno',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2026,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 2.4,
            direcao: 92,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Terzo_Millennio: {
            imagem: './Imgs_Carros/Lamborghini/LamboTerzoMillennio.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Terzo Millennio',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2017,
            pais: 'Itália',
            velocidade: 354,
            aceleracao: 1.9,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Asterion: {
            imagem: './Imgs_Carros/Lamborghini/LamboAsterion.png',
            logo: './assets/Lamborghini-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Asterion',
            montadora: 'Lamborghini',
            classe: "S",
            ano: 2014,
            pais: 'Itália',
            velocidade: 320,
            aceleracao: 3.0,
            direcao: 84,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        }
    },
    "Nissan": {
        P35: {
            imagem: './Imgs_Carros/Nissan/NissanP35.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'P35',
            montadora: 'Nissan',
            classe: "R",
            ano: 1993,
            pais: 'Japão',
            velocidade: 322,
            aceleracao: 3.5,
            direcao: 81,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        R390: {
            imagem: './Imgs_Carros/Nissan/NissanR390.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'R390',
            montadora: 'Nissan',
            classe: "S",
            ano: 1998,
            pais: 'Japão',
            velocidade: 320,
            aceleracao: 3.5,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        GTR_R35: {
            imagem: './Imgs_Carros/Nissan/NissanGTR_R35.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'GTR R35',
            montadora: 'Nissan',
            classe: "S",
            ano: 2023,
            pais: 'Japão',
            velocidade: 315,
            aceleracao: 2.9,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        GTR_R33: {
            imagem: './Imgs_Carros/Nissan/NissanGTR_R33.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'GTR R33',
            montadora: 'Nissan',
            classe: "S",
            ano: 1998,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 5.2,
            direcao: 83,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Nissan350Z: {
            imagem: './Imgs_Carros/Nissan/Nissan350Z.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: '350Z',
            montadora: 'Nissan',
            classe: "A",
            ano: 2009,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 5.7,
            direcao: 77,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Nissan370Z: {
            imagem: './Imgs_Carros/Nissan/Nissan370Z.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: '370Z',
            montadora: 'Nissan',
            classe: "A",
            ano: 2020,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 5.1,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Z_Proto: {
            imagem: './Imgs_Carros/Nissan/NissanZ.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Z Proto',
            montadora: 'Nissan',
            classe: "S",
            ano: 2022,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.5,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Skyline_R34: {
            imagem: './Imgs_Carros/Nissan/NissanGTR_R34.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Skyline R34',
            montadora: 'Nissan',
            classe: "S",
            ano: 2002,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.9,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Silvia_S15: {
            imagem: './Imgs_Carros/Nissan/NissanSilviaS15.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Silvia S15',
            montadora: 'Nissan',
            classe: "B",
            ano: 2002,
            pais: 'Japão',
            velocidade: 235,
            aceleracao: 5.5,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Frontier: {
            imagem: './Imgs_Carros/Nissan/NissanFrontier.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Frontier',
            montadora: 'Nissan',
            classe: "D",
            ano: 2025,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.9,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Titan: {
            imagem: './Imgs_Carros/Nissan/NissanTitan.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Titan',
            montadora: 'Nissan',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 185,
            aceleracao: 7.5,
            direcao: 75,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Armada: {
            imagem: './Imgs_Carros/Nissan/NissanArmada.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Armada',
            montadora: 'Nissan',
            classe: "D",
            ano: 2007,
            pais: 'Japão',
            velocidade: 183,
            aceleracao: 7.4,
            direcao: 73,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Patrol: {
            imagem: './Imgs_Carros/Nissan/NissanPatrol.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Patrol',
            montadora: 'Nissan',
            classe: "A",
            ano: 2025,
            pais: 'Japão',
            velocidade: 210,
            aceleracao: 6.3,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Versa: {
            imagem: './Imgs_Carros/Nissan/NissanVersa.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Versa',
            montadora: 'Nissan',
            classe: "E",
            ano: 2025,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 9.0,
            direcao: 78,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Pintara: {
            imagem: './Imgs_Carros/Nissan/NissanPintara.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Pintara',
            montadora: 'Nissan',
            classe: "E",
            ano: 1992,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 9.5,
            direcao: 64,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Presea: {
            imagem: './Imgs_Carros/Nissan/NissanPresea.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Presea',
            montadora: 'Nissan',
            classe: "E",
            ano: 2000,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 10,
            direcao: 70,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Sentra: {
            imagem: './Imgs_Carros/Nissan/NissanSentra.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Sentra',
            montadora: 'Nissan',
            classe: "C",
            ano: 2025,
            pais: 'Japão',
            velocidade: 200,
            aceleracao: 9.4,
            direcao: 75,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Tiida: {
            imagem: './Imgs_Carros/Nissan/NissanTiida.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Tiida',
            montadora: 'Nissan',
            classe: "E",
            ano: 2008,
            pais: 'Japão',
            velocidade: 190,
            aceleracao: 9,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Nissan180SX: {
            imagem: './Imgs_Carros/Nissan/Nissan180SX.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: '180SX',
            montadora: 'Nissan',
            classe: "C",
            ano: 1998,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 8.9,
            direcao: 76,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Nissan240Z: {
            imagem: './Imgs_Carros/Nissan/Nissan240Z.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: '240Z',
            montadora: 'Nissan',
            classe: "C",
            ano: 1970,
            pais: 'Japão',
            velocidade: 200,
            aceleracao: 7.8,
            direcao: 77,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        March: {
            imagem: './Imgs_Carros/Nissan/NissanMarch.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'March',
            montadora: 'Nissan',
            classe: "E",
            ano: 2018,
            pais: 'Japão',
            velocidade: 170,
            aceleracao: 10.5,
            direcao: 73,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Be_1: {
            imagem: './Imgs_Carros/Nissan/NissanBe1.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Be 1',
            montadora: 'Nissan',
            classe: "E",
            ano: 1988,
            pais: 'Japão',
            velocidade: 136,
            aceleracao: 16.9,
            direcao: 60,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Pixo: {
            imagem: './Imgs_Carros/Nissan/NissanPixo.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Pixo',
            montadora: 'Nissan',
            classe: "E",
            ano: 2013,
            pais: 'Japão',
            velocidade: 160,
            aceleracao: 13.5,
            direcao: 63,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Leaf: {
            imagem: './Imgs_Carros/Nissan/NissanLeaf.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Leaf',
            montadora: 'Nissan',
            classe: "E",
            ano: 2022,
            pais: 'Japão',
            velocidade: 144,
            aceleracao: 7.9,
            direcao: 66,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        XTerra: {
            imagem: './Imgs_Carros/Nissan/NissanXTerra.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'XTerra',
            montadora: 'Nissan',
            classe: "E",
            ano: 2015,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.0,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Kicks_2015: {
            imagem: './Imgs_Carros/Nissan/NissanKicks2015.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Kicks',
            montadora: 'Nissan',
            classe: "E",
            ano: 2015,
            pais: 'Japão',
            velocidade: 175,
            aceleracao: 12.0,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Kicks_2026: {
            imagem: './Imgs_Carros/Nissan/NissanKicks2026.png',
            logo: './assets/Nissan-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Kicks',
            montadora: 'Nissan',
            classe: "E",
            ano: 2026,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.5,
            direcao: 69,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "Ferrari": {
        Enzo: {
            imagem: './Imgs_Carros/Ferrari/FerrariEnzo.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Enzo',
            montadora: 'Ferrari',
            classe: "X",
            ano: 2004,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 45811,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        F80: {
            imagem: './Imgs_Carros/Ferrari/FerrariF80.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F80',
            montadora: 'Ferrari',
            classe: "R",
            ano: 2026,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 45690,
            direcao: 88,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        LaFerrari: {
            imagem: './Imgs_Carros/Ferrari/FerrariLaFerrari.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'LaFerrari',
            montadora: 'Ferrari',
            classe: "R",
            ano: 2015,
            pais: 'Itália',
            velocidade: 350,
            aceleracao: 45779,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Ferrari_499P: {
            imagem: './Imgs_Carros/Ferrari/Ferrari499P.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '499P',
            montadora: 'Ferrari',
            classe: "R",
            ano: 2023,
            pais: 'Itália',
            velocidade: 347,
            aceleracao: 45690,
            direcao: 99,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        FXX_K_EVO: {
            imagem: './Imgs_Carros/Ferrari/FerrariFXXKEVO.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'FXX K EVO',
            montadora: 'Ferrari',
            classe: "R",
            ano: 2017,
            pais: 'Itália',
            velocidade: 342,
            aceleracao: 45779,
            direcao: 95,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        F12_Berlinetta: {
            imagem: './Imgs_Carros/Ferrari/FerrariF12Berlinetta.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F12 Berlinetta',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2017,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 45660,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        F8_Tributo: {
            imagem: './Imgs_Carros/Ferrari/FerrariF8Tributo.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F8 Tributo',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2023,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 45902,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        SF90_Stradale: {
            imagem: './Imgs_Carros/Ferrari/FerrariSF90Stradale.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'SF90 Stradale',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 45779,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Ferrari_12Cilindri: {
            imagem: './Imgs_Carros/Ferrari/Ferrari12Cilindri.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '12Cilindri',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 340,
            aceleracao: 45902,
            direcao: 86,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Ferrari_599_GTO: {
            imagem: './Imgs_Carros/Ferrari/Ferrari599GTO.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '599 GTO',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2011,
            pais: 'Itália',
            velocidade: 335,
            aceleracao: 45750,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        FF: {
            imagem: './Imgs_Carros/Ferrari/FerrariFF.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'FF',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2016,
            pais: 'Itália',
            velocidade: 335,
            aceleracao: 45841,
            direcao: 79,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        GTC4Lusso: {
            imagem: './Imgs_Carros/Ferrari/FerrariGTC4Lusso.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'GTC4Lusso',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2020,
            pais: 'Itália',
            velocidade: 335,
            aceleracao: 45750,
            direcao: 86,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Ferrari_599XX: {
            imagem: './Imgs_Carros/Ferrari/Ferrari599XX.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '599XX',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2009,
            pais: 'Itália',
            velocidade: 332,
            aceleracao: 45902,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Ferrari_296_GTB: {
            imagem: './Imgs_Carros/Ferrari/Ferrari296GTB.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '296 GTB',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2021,
            pais: 'Itália',
            velocidade: 331,
            aceleracao: 45902,
            direcao: 87,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Ferrari_488_GTB: {
            imagem: './Imgs_Carros/Ferrari/Ferrari488GTB.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '488 GTB',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2019,
            pais: 'Itália',
            velocidade: 330,
            aceleracao: 3,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Ferrari_458_Speciale: {
            imagem: './Imgs_Carros/Ferrari/Ferrari458Speciale.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '458 Speciale',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2015,
            pais: 'Itália',
            velocidade: 325,
            aceleracao: 3,
            direcao: 84,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        F50: {
            imagem: './Imgs_Carros/Ferrari/FerrariF50.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F50',
            montadora: 'Ferrari',
            classe: "S",
            ano: 1995,
            pais: 'Itália',
            velocidade: 325,
            aceleracao: 45903,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        F40: {
            imagem: './Imgs_Carros/Ferrari/FerrariF40.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F40',
            montadora: 'Ferrari',
            classe: "S",
            ano: 1993,
            pais: 'Itália',
            velocidade: 323,
            aceleracao: 45661,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Amalfi: {
            imagem: './Imgs_Carros/Ferrari/FerrariAmalfi.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Amalfi',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2026,
            pais: 'Itália',
            velocidade: 321,
            aceleracao: 45719,
            direcao: 83,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Portofino: {
            imagem: './Imgs_Carros/Ferrari/FerrariPortofino.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Portofino',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2023,
            pais: 'Itália',
            velocidade: 321,
            aceleracao: 45780,
            direcao: 82,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Roma: {
            imagem: './Imgs_Carros/Ferrari/FerrariRoma.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Roma',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 321,
            aceleracao: 45750,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        F430: {
            imagem: './Imgs_Carros/Ferrari/FerrariF430.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F430',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2009,
            pais: 'Itália',
            velocidade: 316,
            aceleracao: 4,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        California: {
            imagem: './Imgs_Carros/Ferrari/FerrariCalifornia.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'California',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2017,
            pais: 'Itália',
            velocidade: 316,
            aceleracao: 45811,
            direcao: 79,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Purosangue: {
            imagem: './Imgs_Carros/Ferrari/FerrariPurosangue.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Purosangue',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2025,
            pais: 'Itália',
            velocidade: 311,
            aceleracao: 45719,
            direcao: 85,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Berlinetta_Boxer: {
            imagem: './Imgs_Carros/Ferrari/FerrariBerlinettaBoxer.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Berlinetta Boxer',
            montadora: 'Ferrari',
            classe: "S",
            ano: 1976,
            pais: 'Itália',
            velocidade: 301,
            aceleracao: 45752,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Challenge_Stradale: {
            imagem: './Imgs_Carros/Ferrari/FerrariChallengeStradale.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Challenge Stradale',
            montadora: 'Ferrari',
            classe: "S",
            ano: 2005,
            pais: 'Itália',
            velocidade: 300,
            aceleracao: 45661,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        F355_Berlinetta: {
            imagem: './Imgs_Carros/Ferrari/FerrariF355Berlinetta.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'F355 Berlinetta',
            montadora: 'Ferrari',
            classe: "A",
            ano: 1999,
            pais: 'Itália',
            velocidade: 295,
            aceleracao: 45842,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Mondial: {
            imagem: './Imgs_Carros/Ferrari/FerrariMondial32.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: 'Mondial 3.2',
            montadora: 'Ferrari',
            classe: "A",
            ano: 1989,
            pais: 'Itália',
            velocidade: 250,
            aceleracao: 45754,
            direcao: 71,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Ferrari_250: {
            imagem: './Imgs_Carros/Ferrari/Ferrari250.png',
            logo: './assets/Ferrari-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Itália',
            nome: '250',
            montadora: 'Ferrari',
            classe: "B",
            ano: 1953,
            pais: 'Itália',
            velocidade: 218,
            aceleracao: 45816,
            direcao: 63,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        }
    }
};

const allCards = {};
for (const manufacturer in manufacturers) {
    Object.assign(allCards, manufacturers[manufacturer]);
}

// Torna 'manufacturers' e 'cards' globais para que possam ser acessados por outros scripts.
// E exporta-os para uso com importações de módulo.
window.manufacturers = manufacturers;
window.cards = allCards;

export { allCards as cards, manufacturers };
