// cards.js

// A base de dados agora está organizada por montadora para facilitar a manutenção.
const manufacturers = {
    "Toyota": {
       Supra_MK5: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK5.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK5 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 2022,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.5,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Supra_MK4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASupraMK4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Supra MK4 3.0',
            montadora: 'Toyota',
            classe: "A",
            ano: 1995,
            pais: 'Japão',
            velocidade: 250,
            aceleracao: 4.6,
            direcao: 77,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Corolla_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAGRCorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR 1.6',
            montadora: 'Toyota',
            classe: "B",
            ano: 2024,
            pais: 'Japão',
            velocidade: 230,
            aceleracao: 5.5,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Corolla: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorolla.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Altis 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_GR_Sport: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 205,
            aceleracao: 9.2,
            direcao: 78,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        Camry: {
            imagem: './Imgs_Carros/Toyota/TOYOTACamry.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Camry XLE 3.5 V6',
            montadora: 'Toyota',
            classe: "C",
            ano: 2020,
            pais: 'Japão',
            velocidade: 225,
            aceleracao: 7,
            direcao: 76,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCross.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross XRX 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Corolla_Cross_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTACorollaCrossGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Corolla Cross GR Sport 2.0',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 9.8,
            direcao: 73,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        RAV4: {
            imagem: './Imgs_Carros/Toyota/TOYOTARAV4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'RAV4 2.5 PHEV',
            montadora: 'Toyota',
            classe: "C",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 6,
            direcao: 75,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        AE86: {
            imagem: './Imgs_Carros/Toyota/TOYOTAAE86.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Toyota AE86 BEV',
            montadora: 'Toyota',
            classe: "D",
            ano: 1986,
            pais: 'Japão',
            velocidade: 195,
            aceleracao: 8.9,
            direcao: 57,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        SW4: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 SRX Platinum 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        SW4_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTASW4GR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'SW4 GR Sport 2.8',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Hilux: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHilux.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 12,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Hilux_GR: {
            imagem: './Imgs_Carros/Toyota/TOYOTAHiluxGR.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Hilux Conquest 2.8 Turbo',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 10.7,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Yaris_Sedan: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisSedan.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Sedan XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 182,
            aceleracao: 11.8,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yaris_Hatch: {
            imagem: './Imgs_Carros/Toyota/TOYOTAYarisHatch.png',
            logo: './assets/Toyota-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=Japão',
            nome: 'Yaris Hatch XLS 1.5',
            montadora: 'Toyota',
            classe: "D",
            ano: 2024,
            pais: 'Japão',
            velocidade: 180,
            aceleracao: 11.8,
            direcao: 68,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "Byd": {
        Han_Ev: {
            imagem: './Imgs_Carros/Byd/BYDHanEv.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Han Ev',
            montadora: 'Byd',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 186,
            aceleracao: 3.9,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Tan_EV: {
            imagem: './Imgs_Carros/Byd/BYDTanEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tan EV',
            montadora: 'Byd',
            classe: "B",
            ano: 2023,
            pais: 'China',
            velocidade: 186,
            aceleracao: 4.6,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Seal: {
            imagem: './Imgs_Carros/Byd/BYDSeal.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Seal',
            montadora: 'Byd',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 3.8,
            direcao: 75,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Shark: {
            imagem: './Imgs_Carros/Byd/BYDShark.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Shark',
            montadora: 'Byd',
            classe: "B",
            ano: 2025,
            pais: 'China',
            velocidade: 160,
            aceleracao: 5.7,
            direcao: 80,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Song_Plus: {
            imagem: './Imgs_Carros/Byd/BYDSongPlus.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Song Plus DM-i 1.5',
            montadora: 'Byd',
            classe: "C",
            ano: 2024,
            pais: 'China',
            velocidade: 170,
            aceleracao: 8.5,
            direcao: 79,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Song_Plus2026: {
            imagem: './Imgs_Carros/Byd/BYDSongPlus2026.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Song Plus DM-i 1.5',
            montadora: 'Byd',
            classe: "C",
            ano: 2026,
            pais: 'China',
            velocidade: 170,
            aceleracao: 7.9,
            direcao: 81,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Yuan_Plus_EV: {
            imagem: './Imgs_Carros/Byd/BYDYuanPlusEV.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Yuan Plus EV',
            montadora: 'Byd',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 7.3,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin: {
            imagem: './Imgs_Carros/Byd/BYDDolphin.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Diamond',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 10.9,
            direcao: 65,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Dolphin_Mini: {
            imagem: './Imgs_Carros/Byd/BYDDolphinMini.png',
            logo: './assets/Byd-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Dolphin Mini EV',
            montadora: 'Byd',
            classe: "E",
            ano: 2024,
            pais: 'China',
            velocidade: 130,
            aceleracao: 14.9,
            direcao: 63,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        }
    },
    "GWM": {
        Haval_H6_GT: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6GT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 GT 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.8,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Haval_H6: {
            imagem: './Imgs_Carros/GWM/GWMHavalH6.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Haval H6 Premium 1.5 PHEV',
            montadora: 'GWM',
            classe: "B",
            ano: 2024,
            pais: 'China',
            velocidade: 180,
            aceleracao: 4.9,
            direcao: 76,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Ora_GT: {
            imagem: './Imgs_Carros/GWM/GWMOraGT.png',
            logo: './assets/GWM-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Ora 03 GT',
            montadora: 'GWM',
            classe: "D",
            ano: 2024,
            pais: 'China',
            velocidade: 160,
            aceleracao: 8.2,
            direcao: 70,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        }
    },
    "Chery": {
        Tiggo_8_Pro: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo8Pro.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 8 Pro Hybrid 1.5',
            montadora: 'Chery',
            classe: "C",
            ano: 2025,
            pais: 'China',
            velocidade: 180,
            aceleracao: 7,
            direcao: 72,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Tiggo_7_Sport: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo7Sport.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 7 Sport 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 180,
            aceleracao: 10.3,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Tiggo_5x_Sport: {
            imagem: './Imgs_Carros/Chery/CHERYTiggo5xSport.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Tiggo 5x Sport 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 193,
            aceleracao: 10.7,
            direcao: 67,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Arrizo_5: {
            imagem: './Imgs_Carros/Chery/CHERYArrizo5.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Arrizo 5 RXS 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2021,
            pais: 'China',
            velocidade: 190,
            aceleracao: 9.9,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Arrizo_6_Pro: {
            imagem: './Imgs_Carros/Chery/CHERYArrizo6Pro.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'Arrizo 6 Pro Hybrid 1.5',
            montadora: 'Chery',
            classe: "D",
            ano: 2025,
            pais: 'China',
            velocidade: 190,
            aceleracao: 9,
            direcao: 71,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        QQ: {
            imagem: './Imgs_Carros/Chery/CHERYQQ.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'QQ Look 1.0',
            montadora: 'Chery',
            classe: "E",
            ano: 2020,
            pais: 'China',
            velocidade: 165,
            aceleracao: 14,
            direcao: 59,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        iCar: {
            imagem: './Imgs_Carros/Chery/CHERYiCar.png',
            logo: './assets/Chery-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=China',
            nome: 'iCar EQ1 Tech',
            montadora: 'Chery',
            classe: "E",
            ano: 2021,
            pais: 'China',
            velocidade: 120,
            aceleracao: 12.9,
            direcao: 60,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
    },
    "LandRover": {
        Range_Rover_Sport: {
            imagem: './Imgs_Carros/LandRover/LANDROVERRangeRoverSport.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Range Rover Sport Dynamic',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 234,
            aceleracao: 5.9,
            direcao: 74,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Discovery: {
            imagem: './Imgs_Carros/LandRover/LANDROVERDiscovery.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Discovery R-Dynamic 3.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "C",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 209,
            aceleracao: 6.8,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Evoque: {
            imagem: './Imgs_Carros/LandRover/LANDROVEREvoque.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Evoque HSE Dynamic 2.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "C",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 230,
            aceleracao: 7.5,
            direcao: 73,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Range_Rover: {
            imagem: './Imgs_Carros/LandRover/LANDROVERRangeRover.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Range Rover Vogue SE 5.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2015,
            pais: 'Reino Unido',
            velocidade: 250,
            aceleracao: 5.5,
            direcao: 71,
            altura: 'Alto',
            pneus: 'Desempenho',
            tracao: '4x4'
        },
        Velar: {
            imagem: './Imgs_Carros/LandRover/LANDROVERVelar.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Velar R-Dynamic HSE 2.0',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "B",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 209,
            aceleracao: 5.4,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Defender: {
            imagem: './Imgs_Carros/LandRover/LANDROVERDefender.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Defender 130 X 3.00',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "D",
            ano: 2024,
            pais: 'Reino Unido',
            velocidade: 191,
            aceleracao: 7.5,
            direcao: 72,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Freelander: {
            imagem: './Imgs_Carros/LandRover/LANDROVERFreelander.png',
            logo: './assets/LandRover-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=UK',
            nome: 'Freelander HSE 2.2',
            montadora: 'LandRover', // Corrigido: sem espaço
            classe: "D",
            ano: 2015,
            pais: 'Reino Unido',
            velocidade: 190,
            aceleracao: 9.5,
            direcao: 66,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        }
    },
    "Chevrolet": {
        CorvetteZ062015: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062015.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2015,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 3,
            direcao: 80,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        CorvetteZ062023: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062023.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 5.5 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2023,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 2.8,
            direcao: 90,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Corvette_Stingray: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteStingray.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Stingray 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2020,
            pais: 'EUA',
            velocidade: 330,
            aceleracao: 3,
            direcao: 85,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        CorvetteZ062006: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCorvetteZ062006.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Corvette Z06 7.0 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2006,
            pais: 'EUA',
            velocidade: 305,
            aceleracao: 5.1,
            direcao: 73,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Camaro_Collection: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroCollection.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro Collection 6.2 V8',
            montadora: 'Chevrolet',
            classe: "S",
            ano: 2024,
            pais: 'EUA',
            velocidade: 290,
            aceleracao: 4.2,
            direcao: 84,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Camaro_SS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroSS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro SS 6.2 V8',
            montadora: 'Chevrolet',
            classe: "A",
            ano: 2012,
            pais: 'EUA',
            velocidade: 250,
            aceleracao: 4.8,
            direcao: 81,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Camaro_Conversível_SS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCamaroConversívelSS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Camaro Conversível SS 6.2',
            montadora: 'Chevrolet',
            classe: "A",
            ano: 2019,
            pais: 'EUA',
            velocidade: 250,
            aceleracao: 4.2,
            direcao: 83,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Silverado: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETSilverado.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Silverado High Country 5.3',
            montadora: 'Chevrolet',
            classe: "C",
            ano: 2024,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 7.4,
            direcao: 78,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
       Cruze_Hatch_RS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCruzeHatch.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Cruze Hatch RS 1.4 Turbo',
            montadora: 'Chevrolet',
            classe: "C",
            ano: 2024,
            pais: 'EUA',
            velocidade: 214,
            aceleracao: 9,
            direcao: 73,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        S10_2025: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETS102025.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'S10 High Country 2.8',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 9.4,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
        Trail_Blazer: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETTrailBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'TrailBlazer Premier 2.8',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2024,
            pais: 'EUA',
            velocidade: 180,
            aceleracao: 10.3,
            direcao: 70,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: '4x4'
        },
       Equinox: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETEquinox.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Equinox Premier 1.5',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2024,
            pais: 'EUA',
            velocidade: 196,
            aceleracao: 9.2,
            direcao: 69,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: '4x4'
        },
        Onix_Sedan: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOnixSedan.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Onix Sedan Premier 1.0',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 187,
            aceleracao: 10.4,
            direcao: 69,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Onix_RS: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOnixRS.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Onix RS 1.0 Turbo',
            montadora: 'Chevrolet',
            classe: "D",
            ano: 2025,
            pais: 'EUA',
            velocidade: 187,
            aceleracao: 10.1,
            direcao: 71,
            altura: 'Baixo',
            pneus: 'Desempenho',
            tracao: 'Dianteira'
        },
        Bolt: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETBolt.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Bolt Premier',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2022,
            pais: 'EUA',
            velocidade: 146,
            aceleracao: 7.3,
            direcao: 67,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Celta: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCelta.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Celta LT 1.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2015,
            pais: 'EUA',
            velocidade: 161,
            aceleracao: 13.4,
            direcao: 56,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Agile: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETAgile.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Agile Effect 1.4',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2014,
            pais: 'EUA',
            velocidade: 177,
            aceleracao: 10.9,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Astra: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETAstra.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Astra Advantage 2.0 8V',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2011,
            pais: 'EUA',
            velocidade: 200,
            aceleracao: 9.8,
            direcao: 64,
            altura: 'Baixo',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Blazer_2011: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Blazer Advantage 2.4',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2011,
            pais: 'EUA',
            velocidade: 150,
            aceleracao: 11.9,
            direcao: 60,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Grand_Blazer: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETGrandBlazer.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Grand Blazer 4.2',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 2000,
            pais: 'EUA',
            velocidade: 150,
            aceleracao: 18,
            direcao: 56,
            altura: 'Alto',
            pneus: 'Off-Road',
            tracao: 'Traseira'
        },
        Monza: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETMonza.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Monza GLS 2.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1996,
            pais: 'EUA',
            velocidade: 172,
            aceleracao: 11.7,
            direcao: 67,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Chevy_500: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevy500.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevy 500 DL 1.6',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1995,
            pais: 'EUA',
            velocidade: 140,
            aceleracao: 18.5,
            direcao: 50,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Dianteira'
        },
        Chevette_Junior: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevetteJunior.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevette Junior 1.0',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1993,
            pais: 'EUA',
            velocidade: 131,
            aceleracao: 21.6,
            direcao: 60,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Opala: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETOpala.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Opala SL 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 169,
            aceleracao: 12,
            direcao: 65,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Caravan_Comodoro: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCaravanComodoro.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Caravan Comodoro 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 168,
            aceleracao: 12.1,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Desempenho',
            tracao: 'Traseira'
        },
        Caravan_Diplomata: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETCaravanDiplomata.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Caravan Diplomata 4.1',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1992,
            pais: 'EUA',
            velocidade: 168,
            aceleracao: 12.1,
            direcao: 62,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
        Chevette_1990: {
            imagem: './Imgs_Carros/Chevrolet/CHEVROLETChevette1990.png',
            logo: './assets/Chevrolet-Logo.png',
            bandeira: 'https://placehold.co/40x30/ffffff/000000?text=EUA',
            nome: 'Chevette SL 1.6',
            montadora: 'Chevrolet',
            classe: "E",
            ano: 1990,
            pais: 'EUA',
            velocidade: 151,
            aceleracao: 14.1,
            direcao: 57,
            altura: 'Médio',
            pneus: 'Padrão',
            tracao: 'Traseira'
        },
    }
};

const allCards = {};
for (const manufacturer in manufacturers) {
    Object.assign(allCards, manufacturers[manufacturer]);
}

// Torna 'manufacturers' e 'cards' globais para que possam ser acessados por outros scripts.
// E exporta-os para uso com importações de módulo.
window.manufacturers = manufacturers;
window.cards = allCards;

export { allCards as cards, manufacturers };
